### ISSUE TITLE
Allow attribute opt-in

### ISSUE THREAD

**Issue by matkoch** [ulrichb/XmlDocInspections#10]
I would like to opt-in required XML documentation by using attributes.

Background is that I'm already facilitating attributes to mark certain "public API" types/methods, which inherently means that they should have a proper documentation.

**Comment by matkoch** [comment]
Any news?

**Comment by ulrichb** [comment]
Released in 2.0.0

**Comment by matkoch** [comment]
Any news?

**Comment by matkoch** [comment]
Einfach stark :)
