### ISSUE TITLE
Missing warning for public member in internal type.

### ISSUE THREAD

**Issue by sq735** [ulrichb/XmlDocInspections#14]
Hello, I have the follow XmlDocInspections setting:
![er](https://user-images.githubusercontent.com/19763214/49313688-25063d00-f4f9-11e8-99f6-a5174be52b20.png)

But nonetheless warning for public member in internal type is missing. Is it the bug?

![er1](https://user-images.githubusercontent.com/19763214/49313802-79a9b800-f4f9-11e8-93e6-114d73f799e1.png)

**Comment by ulrichb** [comment]
What you observe is ReSharper's interpretation of `AccessibilityDomainType.PUBLIC`/`.INTERNAL`, which implements the rule that internal class + public member _effectively_ is internal. => Expected behavior.
