### ISSUE TITLE
Missing Warning for public members when using ResharperCommandlineTools

### ISSUE THREAD

**Issue by Khamulus** [ulrichb/XmlDocInspections#15]
Hello,

We are using Resharper 2020.2.4 and the latest version of XmlDocInspections (2.11.0.7380202) in Visual Studio 2019

We see the warning / error when inspecting the code in visual studio, but when we run the inspection with the ResharperCommandlineTools on our build machines, the warning / error is not present in the XML.

It worked perfectly with older versions of ResharperCommandlineTools (before 2020.2.x).

greetings from Austria

**Comment by ulrichb** [comment]
Sorry, cannot reproduce . Just tested my sample solution against R# CLT 2020.2.4 and it works...

**Comment by matkoch** [comment]
What version of ReSharper CLTs are you using?

**Comment by Khamulus** [comment]
Thanx for the fast answer

we are using the latest version of CLT 2020.2.4, same version in VS

Ive just created a test project
This is the result of InspectCode in VS
![ReSharper_VS](https://user-images.githubusercontent.com/1622716/97045854-d04d8e80-1576-11eb-9645-abba8ba89ef4.PNG)

This is the XML generated by our build machine
![ResharperCLT_CI](https://user-images.githubusercontent.com/1622716/97045923-e5c2b880-1576-11eb-95ba-3b76e979d188.PNG)

This is the command we use on our build machine:
_${bamboo.build.working.directory}\ResharperTestProject.sln -o=${bamboo.build.working.directory}\Artifacts\SCA\StaticCodeAnalysis_Errors.xml --swea -x=ReSharper.XmlDocInspections.2.11.0.7380202 -s=ERROR_

removing -s=ERROR dows not change anything (except that warnings and suggestions are in the xml file)

This are our settings (shared as Solution TeamShared) ... there is no .user settings file in the project
![resharper_settings](https://user-images.githubusercontent.com/1622716/97046340-86b17380-1577-11eb-9d02-3481637dfb03.PNG)

**Comment by matkoch** [comment]
I don’t think that the -x switch works. It’s an issue that’s planned to be
fixed for 2020.3.

**Comment by ulrichb** [comment]
Yep, to use `/x` you either have to wait for 2020.3 (see https://youtrack.jetbrains.com/issue/RSRP-436208) or use the workaround mentioned here: https://youtrack.jetbrains.com/issue/RSRP-436208#focus=Comments-27-1667146.0-0

**Comment by Khamulus** [comment]
@ulrichb 
@matkoch 
Thx both of you ... i remember der was something ... looked into the old CLT folders and the nupkg file was present there.

It works now perfectly.
