### ISSUE TITLE
Not supported in 2021.1

### ISSUE THREAD

**Issue by schodemeiss** [ulrichb/XmlDocInspections#17]
Manually updating the package info shows the plugin should work with a simple change to the package. Would be great to get an official update rather than hacking the package, however.

**Comment by ulrichb** [comment]
Oh, thats the first time that this someone asks for at EAP 2 stage 🤗

An official release will be there after RTM. In the meantime you can use the package artifact from the R211 branch. See the TeamCity link on the readme page.

**Comment by ulrichb** [comment]
Released
