### ISSUE TITLE
Enable only when xml-doc generation is enabled

### ISSUE THREAD

**Issue by FabienDehopre** [ulrichb/XmlDocInspections#2]
The hints should only be displayed when the "XML documentation file" option is checked in the project properties.
It's annoying to have these hints requesting to create xml-doc in projects where you don't want to create xml-doc.

**Comment by alexdresko** [comment]
A project wide setting would definitely be nice.

**Comment by ulrichb** [comment]
You could disable XML Doc inspections at solution level (disable all flags on the settings page and save it to "team-shared settings"), and enable it again on project-level, using a `.csproj.DotSettings` file. Unfortunately, R# offers no UI at the moment, [but it's possible](https://blog.jetbrains.com/dotnet/2012/01/18/per-project-settings-or-how-to-have-different-naming-styles-for-my-test-project/).

These would be example settings:
```xml
<s:String x:Key="/Default/CodeInspection/XmlDocInspections/TypeAccessibility/@EntryValue">Public, Protected</s:String>
<s:String x:Key="/Default/CodeInspection/XmlDocInspections/TypeMemberAccessibility/@EntryValue">Public</s:String>
```

@FabienDehopre, @alexdresko Would this solve your problem?

**Comment by alexdresko** [comment]
I thought that might be the fix, but I tried it and it didn't work at the time. I'm familiar with solution specific settings, so not sure why it didn't work. I'll try again.. might have been a user error on my part.

**Comment by ulrichb** [comment]
@alexdresko I've prepared a [sample solution](https://github.com/ulrichb/XmlDocInspections/files/252563/SampleSolution.zip).

**Comment by ulrichb** [comment]
Closed after long period without response.

**Comment by alexdresko** [comment]
Sorry, this has been working fine for a long time now.
