### ISSUE TITLE
Allow skipping warnings for overriding members

### ISSUE THREAD

**Issue by DarkDaskin** [ulrichb/XmlDocInspections#3]
Usually there is no need to explicitly document overriding members as the documentation from the base class is sufficient and is already shown by ReSharper IntelliSense.
An option to disable warnings for such members is required to reduce visual noise. Optionally a sub-option can be added to only skip warnings if the base class member actually has documentation.

**Comment by ulrichb** [comment]
Implemented new setting in 1.5.0.
