### ISSUE TITLE
2016.1 support? 

### ISSUE THREAD

**Issue by alexdresko** [ulrichb/XmlDocInspections#4]
I miss this having this extension after upgrading to R# 2016.1.. 

Does anyone know what it takes to upgrade it?

**Comment by alexdresko** [comment]
Well that was a fun little adventure. I cloned the repo and figured out how to build the nupkg files in the  #R#10.1 branch. `powershell -file build\build.ps1` worked great after I removed the `Test` line (some of the tests failed, and it obviously can't publish the results to your appveyor account. Once the packages were built, I created a new extension source in R# and pointed it at the `build\output` folder and R# found the extension. 

Works like a champ. Is there anything I should know while testing this version?

**Comment by ulrichb** [comment]
Yes. This exactly the way how to build a local package.

Nothing special to know for testing, but note that I haven't ran it with the RTM version yet.

Do you have results? Any issues?

**Comment by alexdresko** [comment]
Seems to be working well. For some reason, I'm not seeing the "references" line that is normally there between the code and the comment, but I don't yet know if that's related to the extension. Will try to do some more testing.

**Comment by ulrichb** [comment]
@alexdresko Yes, I doubt that the missing "references count" is related to R# at all. Could you check the "CodeLens" options? (Tools | Options | Text Editor | All languages | CodeLens.) If it is enabled, try to suspend R# to check if the missing "references count" is a R# issue.

**Comment by alexdresko** [comment]
You're right. Somehow codelense got disabled. All is well. Still no problems with this branch. 

What's keeping you from going live with it?

**Comment by ulrichb** [comment]
@alexdresko Perfect.

Released 1.4.0 with R# 2016.1 support to the [R# gallery](https://resharper-plugins.jetbrains.com/packages/ReSharper.XmlDocInspections). Have fun.
