### ISSUE TITLE
Add Quick-Fix which inserts XML Doc comment template

### ISSUE THREAD

**Issue by alexdresko** [ulrichb/XmlDocInspections#5]
Don't know the terminology. And I'm sure you've thought of this before...

But what's standing in the way of enabling the plugin to fix the issues it finds?

**Comment by ulrichb** [comment]
OK, I need some more details here. Do you mean an `Alt+Enter` quick-fix? If yes, what should it do?

**Comment by alexdresko** [comment]
Don't know if this is possible, but when I type `///` above a method, it automatically inserts a default comment...   

gif demo...

![auto fix comment](https://cloud.githubusercontent.com/assets/333022/15079054/52b55fdc-1384-11e6-9e57-4fd1bc011845.gif)

**Comment by ulrichb** [comment]
So you want a quick-fix for "Missing XML Doc" highlightings, which adds the same doc comment template as typing `///` before the declaration (as in your GIF). Is this the feature request?

**Comment by alexdresko** [comment]
That would meet my expectations, certainly..

**Comment by ulrichb** [comment]
Implemented on [dev](https://github.com/ulrichb/XmlDocInspections/tree/dev) branch. Will be available in the next release together with R# 2017.1 support.

**Comment by alexdresko** [comment]
So super rad! I'm loving it! 

The only thing that could possibly make it more awesome is if you could enable it to optionally add the comments "in this file | in this project | in this solution" as some quick fixes do. I feel bad even suggesting another idea since what you've done is already so massively helpful.

**Comment by ulrichb** [comment]
Released with 1.8.0.

**Comment by ulrichb** [comment]
@alexdresko Regarding your request for a "fix in file/project/solution" feature: I will think about it, but at the moment I tend to do not implement this because the quick fix only generates _templates_ (which have to be edited afterwards). And such a feature possibly misleads people to generate skeleton docs in batch just to silence the warning.

**Comment by alexdresko** [comment]
@ulrichb (and @matkoch) I totally get what you're saying. 

But it's a classic case of users doing something with your application that you never intended. See, my boss thinks it makes code easier to read simply by inserting XML comments. We're not required to fill out the summary -- we just have to insert the initial XML comment tags (which your plugin does _extremely_ well). 

I know. You don't have to tell me. I've tried to convince him otherwise. 

Just try to imagine how much extra time we have to spend ensuring that all of our classes, methods, and properties have XML documentation so my boss can have an easier time reading the code. Maybe then you'll understand how excited I'd be if it were somehow easier. 

I'll understand if you decide not to implement the feature. It makes sense for the reasons you stated. But, then again, maybe we're not the only team that has to endure such torture.

**Comment by alexdresko** [comment]
I know it's a long shot, but I'd still really really really like for this feature to be implemented. It would save me a lot of time.
