### ISSUE TITLE
Suggestions in XAML files? 

### ISSUE THREAD

**Issue by alexdresko** [ulrichb/XmlDocInspections#6]
Definitely don't want to see this in XAML files.. 

![image](https://cloud.githubusercontent.com/assets/333022/14996111/5112105c-1146-11e6-99cc-94fa9629a1b0.png)

**Comment by ulrichb** [comment]
Oh, that's interesting. Will investigate this.

**Comment by alexdresko** [comment]
It's possible this happens because VS generates a C# file in the project when you compile. That generated file is actually a partial file of the XAML file (which itself is really just a class).

**Comment by ulrichb** [comment]
OK. I understand. I'll try to reproduce this.

**Comment by ulrichb** [comment]
Fixed in 1.5.0.
